---
title: "Estimating the Risk of Human Herpesvirus 6 and Cytomegalovirus Transmission to Ugandan Infants from Viral Shedding in Saliva by Household Contacts"
site: workflowr::wflow_site
output:
  workflowr::wflow_html:
    toc: false
---

**Article Authors:** Mayer BT, Krantz E, Wald A, Corey L, Casper C, Gantt S, and Schiffer JT

This article was published in [*Viruses*](https://www.mdpi.com/1999-4915/12/2/171) in 2020 and the [pdf is available there](https://www.mdpi.com/1999-4915/12/2/171/pdf). 

**Citation:** Mayer, B.T.; Krantz, E.M.; Wald, A.; Corey, L.; Casper, C.; Gantt, S.; Schiffer, J.T. Estimating the Risk of Human Herpesvirus 6 and Cytomegalovirus Transmission to Ugandan Infants from Viral Shedding in Saliva by Household Contacts. *Viruses* 2020, 12, 171.

# Analysis Roadmap:

1. [General statistics](general-statistics.html): Overview of the data, survival analysis, and descriptive analysis of exposures.
2. [Transmission modeling](transmission-risk-sensitivity.html): Code that fits transmission models using the survival likelihood optimization and sensitivity analysis. 
3. [Transmission model analysis](transmission-risk.html): Results from the final transmission model: weekly risk estimation by exposure source and dose-response curves.

# Data and other code

- Data and data processing code accessible through the "Data & Figures" tab above.
- Functions used throughout the analysis are [described and displayed here](project-functions.html).

